Repository MamadTaheri68/RN-Jupiter-Team, pull requests merged in 2022-05, with the labels that each got.

#5 Develope
  App.js
  dev-team/03-saeed-mohammadiha.js
  dev-team/04-EmelMousavi.js
  dev-team/Staff.js
  doc/01_SearchBox.png
  doc/02_Product.png
  doc/03_ProductList.png
  doc/04_UI.png
  doc/README.md
  doc/Sample Products List.png
  package.json
  src/assets/styles/productStyle.js
  src/components/ProductList.js
  src/components/Products.js
  yarn.lock
Labels: enhancement, ساختار کلی پروژه

#12 add Skeleton to product Component
  App.js
  src/assets/styles/productStyle.js
  src/components/Product.js
  src/components/ProductList.js
  src/components/Products.js
Labels: ساخت کامپوننت

#14 edit component proucts
  App.js
  src/components/Product.js
  src/components/ProductList.js
Labels: ساخت کامپوننت

#15 connect productList with api
  App.js
  src/assets/styles/productStyle.js
  src/components/Product.js
  src/components/ProductList.js
  yarn.lock
Labels: ساخت کامپوننت, ساختار کلی پروژه

#16 setting rtl app android
  android/app/src/main/java/com/rnjupiterteam/MainApplication.java
Labels: ساختار کلی پروژه

#17 Develope
  App.js
  android/app/src/main/java/com/rnjupiterteam/MainApplication.java
  doc/Untitled.png
  package-lock.json
  package.json
  src/assets/icons/approve.png
  src/assets/icons/react.png
  src/assets/icons/reject.png
  src/assets/styles/productStyle.js
  src/components/Product.js
  src/components/ProductList.js
  src/components/Products.js
  src/components/SearchBox.js
  src/components/Welcome.js
  src/services/SearchProductsByTitleService.js
  yarn.lock
Labels: ساخت کامپوننت, ساخت سرویس, ساختار کلی پروژه

#21 add redux
  App.js
  package.json
  src/redux/action/index.js
  src/redux/reducer/index.js
  src/redux/reducer/producReducer.js
  src/redux/store/index.js
  yarn.lock
Labels: ساختار کلی پروژه

#27 handel pagination with requst api and redux
  App.js
  index.js
  src/assets/styles/ProductsLisrStyle.js
  src/assets/styles/productStyle.js
  src/components/ProductList.js
  src/redux/action/productAction.js
  src/redux/reducer/producReducer.js
  src/services/PageingProductsByTitleService.js
  src/services/SearchProductsByTitleService.js
  src/services/index.js
Labels: ساخت کامپوننت, ساخت سرویس, ساختار کلی پروژه
